name: running tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      go:
        image: golang
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: checkout repo
        uses: actions/checkout@master

      - name: install dependencies
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: migrate database
        run: PATH=$PATH:$HOME/go/bin make migration_up

      - name: running tests
        run: go test ./...
